version: '3.8'

services:
  postgres:
    build:
      context: ./backend
      dockerfile: postgresql.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=instamaps
      - POSTGRES_PASSWORD=instamaps
      - POSTGRES_DB=instamaps
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U instamaps"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend/instamap-core-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=instamaps
      - POSTGRES_PASSWORD=instamaps
      - POSTGRES_DB=instamaps
      - SECRET_KEY=your-super-secret-key-here
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      - ./backend/instamap-core-api:/app

volumes:
  postgres_data:
    driver: local